**无法跨线程捕获异常，异常只能在当前线程捕获：**

```c#
using System;
using System.Threading;
using System.Threading.Tasks;

namespace ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            try
            {

                Task.Run(() =>
                {
                    while (true)
                    {
                        Console.WriteLine("loop in task ..");
                        Thread.Sleep(3000);
                        throw new Exception("error has occured.");  //此处的异常不会被 catch 到，但是此 Task 所在线程会悄无声息的停止运行。
                    }
                });

                Console.WriteLine("outside the task loop .");
                Console.ReadKey();
            }
            catch (Exception ex)
            {
                Console.WriteLine("catch the ex:" + ex.Message);
                Console.ReadKey();
            }
        }
    }
}
```

``必须在线程内捕获异常。``
